#!/bin/bash

export CONSUMER_KEY='XXXXXXXXXXXXXXXXXXXXXX'
																						 
export CONSUMER_SECRET='XXXXXXXXXXXXXXXXXXXXXX'

export TOKEN='XXXXXXXXXXXXXXXXXXXXXXXXXXX'

export TOKEN_SECRET='XXXXXXXXXXXXXXXXXXXXXX'

export PORT=9000